### ISSUE TITLE
Winter has come for me: I ran play as `root` 

### ISSUE THREAD

**Issue by blaisep-sureify** [robertdebock/ansible-role-certbot#7]
## Describe the bug

IDK if this is a bug ... or just a foolish attempt to workaround the "... role must run as root" situation. I tried several permutations of become and eventually ran prepare.yml and converge.yaml as the user called `root`

now I will burn in hell as I try to find out why:
```
Jul 09 07:14:29 ip-10-0-2-129.us-west-1.compute.internal httpd[8496]: httpd: Syntax error on line 360 of /etc/httpd/conf/httpd.conf: Could not open configuration file /etc/httpd/conf.d/zuul_web_ssl.conf: Permission denied>
Jul 09 07:14:29 ip-10-0-2-129.us-west-1.compute.internal systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE
```

## Playbook
```yaml
- name: prepare
  hosts: all
  become_user: fedora
  become_method: sudo
  gather_facts: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.cron
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
      openssl_items:
        - name: apache-httpd
          common_name: "{{ ansible_fqdn }}"
    - role: robertdebock.selinux
    - role: robertdebock.httpd
```
```yaml
---
- name: Install certbot for this domain
  hosts: all
  become: no
  gather_facts: yes

  roles:
    - role: robertdebock.certbot
      certbot_email: blaise@sureify.com
      certbot_domains:
        - ci.sureify.app
      certbot_ci_mode: yes
```

## Output

Show at least the error, possible related output, maybe just all the output.

## Environment
`-rwxr-xr-x. 1 apache apache 1777 Jul  9 07:25 /etc/httpd/conf.d/zuul_web_ssl.conf`
https://softwarefactory-project.io/paste/show/2267/

`httpd.conf` - Ansible Managed
https://softwarefactory-project.io/paste/show/2269/

#### Ansible roles:

https://softwarefactory-project.io/paste/show/2268/

- Control node/managed node is localhost: Fedora 36
Linux ip-10-0-2-129.us-west-1.compute.internal 5.17.13-300.fc36.x86_64 #1 SMP PREEMPT Mon Jun 6 14:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
  config file = /home/fedora/ansible/ansible.cfg
  configured module search path = ['/home/fedora/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fedora/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/fedora/ansible/collections
  executable location = /home/fedora/.local/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = True

(Sponsoring at home as blaisep)
